EXAM_MOCK_BANK = {
    'JEE MAINS': [
        {'q': 'What is the SI unit of electric current?', 'options': ['Watt', 'Ampere', 'Volt'], 'ans': 'B', 'diff': 'Easy'},
        {'q': 'Which element is known as the "King of Chemicals"?', 'options': ['HCl', 'H2SO4', 'HNO3'], 'ans': 'B', 'diff': 'Easy'},
        {'q': 'A car starts from rest and accelerates at 2m/s². What is its velocity after 10 seconds?', 'options': ['10m/s', '20m/s', '40m/s'], 'ans': 'B', 'diff': 'Medium', 'type': 'Numerical'},
        {'q': 'Explain briefly why Water has a higher boiling point than H2S.', 'ans': 'hydrogen bonding', 'diff': 'Medium', 'type': 'Short-answer'},
        {'q': 'What is the pH of a 0.01M HCl solution?', 'options': ['1', '2', '3'], 'ans': 'B', 'diff': 'Medium', 'type': 'Numerical'},
        {'q': 'Evaluate the integral of x² from 0 to 3.', 'ans': '9', 'diff': 'Hard', 'type': 'Numerical'},
        {'q': 'In a Young\'s double slit experiment, if the distance between slits is halved, the fringe width becomes?', 'options': ['Halved', 'Doubled', 'Quadrupled'], 'ans': 'B', 'diff': 'Hard'},
        {'p': 'The Bohr model of the atom represents the first step toward quantum mechanics. Electrons revolve in discrete orbits with quantized angular momentum L = nh/2π. A transition from n=3 to n=2 results in the emission of a photon.', 
         'q': 'Based on the passage, what is the angular momentum of an electron in the 2nd orbit (n=2)?', 'options': ['h/π', 'h/2π', '2h/π'], 'ans': 'A', 'diff': 'Analytical'}
    ],
    'JEE ADVANCED': [
        {'q': 'What is the dimension of the universal gravitational constant G?', 'options': ['[M⁻¹L³T⁻²]', '[ML²T⁻²]', '[M⁻²L³T⁻¹]'], 'ans': 'A', 'diff': 'Easy'},
        {'q': 'Which transition metal has the highest melting point?', 'options': ['Iron', 'Tungsten', 'Mercury'], 'ans': 'B', 'diff': 'Easy'},
        {'q': 'A projectile is fired at 45° with velocity V. What is the ratio of range to maximum height?', 'ans': '4', 'diff': 'Medium', 'type': 'Numerical'},
        {'q': 'Find the area bounded by y=x² and y=x.', 'options': ['1/2', '1/3', '1/6'], 'ans': 'C', 'diff': 'Medium', 'type': 'Numerical'},
        {'q': 'Calculate the work done by one mole of an ideal gas during an isothermal expansion from V to 2V.', 'options': ['RT ln 2', '2RT', 'RT/2'], 'ans': 'A', 'diff': 'Medium', 'type': 'Numerical'},
        {'q': 'If f(x) is a continuous function such that f(x+y) = f(x)f(y), find f\'(0) if f(0)=1.', 'options': ['0', 'f(1)', 'ln(f(1))'], 'ans': 'C', 'diff': 'Hard'},
        {'q': 'A block of mass M is suspended by a string of length L. If a bullet of mass m strikes it with velocity v, find the kinetic energy loss.', 'ans': '0.5mv^2 - 0.5(M+m)V^2', 'diff': 'Hard', 'type': 'Numerical'},
        {'p': 'Entropy (S) is a measure of randomness. The Second Law of Thermodynamics states that the entropy of an isolated system always increases. ΔS = ∫dQ/T. During a spontaneous process, ΔS_total > 0.',
         'q': 'According to the passage, what is the change in entropy for a reversible adiabatic process?', 'options': ['Increases', 'Decreases', 'Zero'], 'ans': 'C', 'diff': 'Analytical'}
    ],
    'NEET': [
        {'q': 'Which part of the human brain controls body temperature?', 'options': ['Cerebellum', 'Hypothalamus', 'Medulla'], 'ans': 'B', 'diff': 'Easy'},
        {'q': 'Define Parthenogenesis in one sentence.', 'ans': 'Asexual reproduction without fertilization', 'diff': 'Easy', 'type': 'Short-answer'},
        {'q': 'A DNA strand has 30% Cytosine. What is the percentage of Adenine?', 'ans': '20', 'diff': 'Medium', 'type': 'Numerical'},
        {'q': 'Which hormone is called the "Master Gland" controller?', 'options': ['Thyroid', 'Pituitary', 'Adrenal'], 'ans': 'B', 'diff': 'Medium'},
        {'q': 'In Mendelian inheritance, what is the phenotypic ratio of a dihybrid cross?', 'options': ['3:1', '1:2:1', '9:3:3:1'], 'ans': 'C', 'diff': 'Medium'},
        {'q': 'If the focal length of a convex lens is 20cm, what is its power (P) in diopters?', 'ans': '5', 'diff': 'Hard', 'type': 'Numerical'},
        {'q': 'Which of the following represents the correct sequence of blood flow?', 'options': ['Atrium -> Ventricle -> Artery', 'Ventricle -> Atrium -> Vein', 'Artery -> Vein -> Atrium'], 'ans': 'A', 'diff': 'Hard'},
        {'p': 'The human heart is a myogenic organ, meaning the heart rate is generated by specialized muscle cells (SA node). Action potentials spread through the AV node, Bundle of His, and Purkinje fibers to ensure synchronous contraction.',
         'q': 'Based on the text, what is the primary pacemaker of the human heart?', 'options': ['AV Node', 'SA Node', 'Purkinje Fibers'], 'ans': 'B', 'diff': 'Analytical'}
    ],
    'KCET': [
        {'q': 'What is the acceleration due to gravity on Earth?', 'options': ['8.9 m/s²', '9.8 m/s²', '10.8 m/s²'], 'ans': 'B', 'diff': 'Easy'},
        {'q': 'The boiling point of water in Kelvin is?', 'ans': '373', 'diff': 'Easy', 'type': 'Numerical'},
        {'q': 'A wire has resistance R. If its length is doubled, what happens to resistance?', 'options': ['R/2', '2R', '4R'], 'ans': 'B', 'diff': 'Medium'},
        {'q': 'Which element is liquid at room temperature?', 'options': ['Silver', 'Bromine', 'Sodium'], 'ans': 'B', 'diff': 'Medium'},
        {'q': 'Find the value of log₁₀(1000).', 'ans': '3', 'diff': 'Medium', 'type': 'Numerical'},
        {'q': 'What is the work done in pulling a 10kg load through 5m? (g=10)', 'ans': '500', 'diff': 'Hard', 'type': 'Numerical'},
        {'q': 'The pH of a solution is 4. Is it acidic or basic?', 'options': ['Acidic', 'Basic', 'Neutral'], 'ans': 'A', 'diff': 'Hard'},
        {'p': 'Newton\'s Third Law states that every action has an equal and opposite reaction. This principle is fundamental to rocket propulsion, where exhaust gases pushed downward create an upward thrust.',
         'q': 'According to the principle described, why does a rocket move upward?', 'options': ['Gravity disappears', 'Reaction to exhaust gases', 'Magnetic levitation'], 'ans': 'B', 'diff': 'Analytical'}
    ],
    'GATE CS/IT': [
        {'q': 'What is the time complexity of QuickSort in the worst case?', 'options': ['O(n)', 'O(n log n)', 'O(n²)'], 'ans': 'C', 'diff': 'Easy'},
        {'q': 'Define "Process" in OS context.', 'ans': 'Program in execution', 'diff': 'Easy', 'type': 'Short-answer'},
        {'q': 'A binary tree has 7 nodes. What is its maximum height (root at 0)?', 'ans': '6', 'diff': 'Medium', 'type': 'Numerical'},
        {'q': 'In SQL, which command is used to remove a table schema?', 'options': ['DELETE', 'TRUNCATE', 'DROP'], 'ans': 'C', 'diff': 'Medium'},
        {'q': 'Which CPU scheduling algorithm can lead to starvation?', 'options': ['Round Robin', 'SJF (Priority)', 'FCFS'], 'ans': 'B', 'diff': 'Medium'},
        {'q': 'Calculate the number of edges in a graph with 5 vertices and 10 degrees total.', 'ans': '5', 'diff': 'Hard', 'type': 'Numerical'},
        {'q': 'What is the 32-bit floating point representation bias?', 'ans': '127', 'diff': 'Hard', 'type': 'Numerical'},
        {'p': 'The OSI model divides network communication into seven layers. The Network Layer (Layer 3) handles routing and IP addressing, while the Data Link Layer (Layer 2) handles MAC addressing and framing.',
         'q': 'Based on the passage, which layer is responsible for IP routing?', 'options': ['Data Link', 'Network', 'Transport'], 'ans': 'B', 'diff': 'Analytical'}
    ],
    'GATE ECE': [
        {'q': 'What is the barrier potential for Silicon?', 'options': ['0.3V', '0.7V', '1.1V'], 'ans': 'B', 'diff': 'Easy'},
        {'q': 'Explain the function of a Zener Diode.', 'ans': 'Voltage regulation', 'diff': 'Easy', 'type': 'Short-answer'},
        {'q': 'Calculate the voltage drop across a 10Ω resistor with 2A current.', 'ans': '20', 'diff': 'Medium', 'type': 'Numerical'},
        {'q': 'A signal is sampled at 4kHz. What is the Nyquist frequency?', 'ans': '2000', 'diff': 'Medium', 'type': 'Numerical'},
        {'q': 'What is the characteristic impedance of free space (rounded)?', 'ans': '377', 'diff': 'Medium', 'type': 'Numerical'},
        {'q': 'Find the gain of an op-amp in inverting mode if Ri=1k and Rf=10k.', 'ans': '-10', 'diff': 'Hard', 'type': 'Numerical'},
        {'q': 'Which modulation technique is most noise-resistant?', 'options': ['AM', 'FM', 'PM'], 'ans': 'B', 'diff': 'Hard'},
        {'p': 'Feedback in amplifiers can be positive or negative. Negative feedback reduces gain but increases bandwidth and stability, making it essential for high-fidelity audio systems.',
         'q': 'According to the passage, what is a primary benefit of negative feedback?', 'options': ['Increased Gain', 'Improved Stability', 'Oscillation'], 'ans': 'B', 'diff': 'Analytical'}
    ],
    'GATE ME': [
        {'q': 'What is the unit of dynamic viscosity?', 'options': ['Pascal', 'Poise', 'N/m'], 'ans': 'B', 'diff': 'Easy'},
        {'q': 'Define "Enthalpy" in one sentence.', 'ans': 'Total heat content of a system', 'diff': 'Easy', 'type': 'Short-answer'},
        {'q': 'Calculate the stress (MPa) on a 10mm² wire under 100N load.', 'ans': '10', 'diff': 'Medium', 'type': 'Numerical'},
        {'q': 'What is the efficiency (%) of a Carnot engine between 300K and 600K?', 'ans': '50', 'diff': 'Medium', 'type': 'Numerical'},
        {'q': 'Which property remains constant during a throttling process?', 'options': ['Entropy', 'Enthalpy', 'Pressure'], 'ans': 'B', 'diff': 'Medium'},
        {'q': 'Find the moment of inertia of a solid cylinder of mass M and radius R about its axis.', 'ans': '0.5MR^2', 'diff': 'Hard', 'type': 'Numerical'},
        {'q': 'What is the Poisson\'s ratio for a perfectly incompressible material?', 'options': ['0', '0.3', '0.5'], 'ans': 'C', 'diff': 'Hard'},
        {'p': 'Forging is a manufacturing process involving the shaping of metal using localized compressive forces. Cold forging occurs at room temperature, while hot forging happens above the recrystallization temperature.',
         'q': 'Based on the text, what determines if forging is "Hot" or "Cold"?', 'options': ['Applied Force', 'Melting Point', 'Recrystallization Temp'], 'ans': 'C', 'diff': 'Analytical'}
    ],
    'COMED-K': [
        {'q': 'What is the value of G (Universal Gravitational Constant) x 10^11?', 'ans': '6.67', 'diff': 'Easy', 'type': 'Numerical'},
        {'q': 'Which acid is found in Ants?', 'options': ['Acetic', 'Citric', 'Formic'], 'ans': 'C', 'diff': 'Easy'},
        {'q': 'Calculate the kinetic energy (J) of a 2kg mass moving at 3m/s.', 'ans': '9', 'diff': 'Medium', 'type': 'Numerical'},
        {'q': 'In a triangle, if sides are 3, 4, 5, is it right-angled?', 'options': ['Yes', 'No', 'Can\'t tell'], 'ans': 'A', 'diff': 'Medium'},
        {'q': 'What is the oxidation state of Oxygen in H₂O?', 'options': ['0', '-1', '-2'], 'ans': 'C', 'diff': 'Medium'},
        {'q': 'Find the focal length (cm) of a mirror with radius 40cm.', 'ans': '20', 'diff': 'Hard', 'type': 'Numerical'},
        {'q': 'The vector product (AxB) is perpendicular to?', 'options': ['Only A', 'Only B', 'Both A and B'], 'ans': 'C', 'diff': 'Hard'},
        {'p': 'Sound waves are longitudinal waves that require a medium to travel. They travel fastest in solids and slowest in gases due to the proximity of particles in the medium.',
         'q': 'Based on the passage, in which medium does sound travel fastest?', 'options': ['Air', 'Water', 'Steel'], 'ans': 'C', 'diff': 'Analytical'}
    ],
    'CUET': [
        {'q': 'What is the synonym of "Resilient"?', 'options': ['Weak', 'Robust', 'Lazy'], 'ans': 'B', 'diff': 'Easy'},
        {'q': 'If a boy is 10 years old and his sister is half his age, how old will she be when he is 20?', 'ans': '15', 'diff': 'Easy', 'type': 'Logic'},
        {'q': 'Solve for x: 3x + 15 = 45.', 'ans': '10', 'diff': 'Medium', 'type': 'Numerical'},
        {'q': 'Which of these is the antonym of "Complex"?', 'options': ['Intricate', 'Simple', 'Tangled'], 'ans': 'B', 'diff': 'Medium'},
        {'q': 'Correct the spelling: Ocurrence / Occurence / Occurrence', 'ans': 'Occurrence', 'diff': 'Medium', 'type': 'Short-answer'},
        {'q': 'If Apple is coded as 1, Banana as 2, what is "Date" coded as?', 'ans': '4', 'diff': 'Hard', 'type': 'Logic'},
        {'q': 'A fruit seller buys 10 oranges for $5. How much for 25?', 'ans': '12.5', 'diff': 'Hard', 'type': 'Numerical'},
        {'p': 'Globalization has transformed the global economy, integrating markets across national borders. While it has increased wealth in many emerging markets, it has also faced criticism for growing inequality and cultural homogenization.',
         'q': 'What is a cited criticism of globalization in the text?', 'options': ['Increased wealth', 'Economic integration', 'Cultural homogenization'], 'ans': 'C', 'diff': 'Analytical'}
    ]
}

ALTERNATIVES = {
    'JEE MAINS': 'KCET, COMED-K, CUET',
    'JEE ADVANCED': 'JEE MAINS, KCET',
    'NEET': 'Allied Health Sciences, Biotechnology, Pharmacy',
    'KCET': 'COMED-K, CUET',
    'GATE CS/IT': 'Coding Certifications, Placement Preparation',
    'GATE ECE': 'Embedded Systems, PSU Preparation',
    'GATE ME': 'Manufacturing/Design Certifications',
    'COMED-K': 'KCET, CUET',
    'CUET': 'State-level Entrance Exams'
}
